# Generated by Django 4.1.1 on 2022-09-27 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('price', 'title', 'article'), 'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
        migrations.CreateModel(
            name='TableOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='время создания')),
                ('is_paid', models.BooleanField(default=False, verbose_name='оплата')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.product', verbose_name='продукт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'корзина',
                'verbose_name_plural': 'корзины',
                'db_table': 'app_tableOrders',
                'ordering': ('date_created', 'is_paid'),
            },
        ),
    ]
